import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "white",
    },
    callContainer: {
        flex: 1,
        paddingBottom: 140,
        paddingHorizontal: 16,
    },
    welcome: {
        fontSize: 30,
        textAlign: "center",
        paddingTop: 40,
    },
    input: {
        minHeight: 90,
        maxHeight: 160,
        borderWidth: 1,
        borderColor: "#D0D5DD",
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        marginHorizontal: 16,
        marginTop: 24,
        textAlignVertical: "top",
        backgroundColor: "#FAFAFA",
        fontSize: 13,
    },
    button: {
        marginTop: 50,
        backgroundColor: "lightblue",
        padding: 10,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        width: 100,
        height: 50,
        alignSelf: "center",
    },
    localVideo: {
        width: 120,
        height: 180,
        borderRadius: 12,
        alignSelf: "flex-end",
    },
    remoteGrid: {
        flex: 1,
        flexDirection: "row",
        flexWrap: "wrap",
    },
    remoteVideo: {
        marginTop: 20,
        marginLeft: 10,
        marginRight: 10,
        width: 100,
        height: 120,
    },
    optionsContainer: {
        position: "absolute",
        left: 16,
        right: 16,
        bottom: 16,
        minHeight: 84,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-evenly",
        backgroundColor: "rgba(255,255,255,0.9)",
        borderRadius: 16,
        paddingHorizontal: 16,
        paddingVertical: 12,
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 10,
        elevation: 4,
    },
    optionButton: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: "#1F2937",
        justifyContent: "center",
        alignItems: "center",
    },

});